import type { Metadata } from "next";
import { ApolloProvider } from '@apollo/client';
import client from '@/lib/apolloClient';
import { geistMono, geistSans } from "@/assets/font";
import "@/assets/styles/globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const fontClass = `${geistSans.variable} ${geistMono.variable} font-sans antialiased`;

  return (
    <html lang="en">
      <body className={fontClass} suppressHydrationWarning>
        <ApolloProvider client={client}>{children}</ApolloProvider>
      </body>
    </html>
  );
}
